# action.yml
name: 'AppCD: Generative IAC'
description: 'Generate IAC from the code'
inputs:
  cmd:
    description: 'Command to run'
    required: true
outputs:
  result:
    description: "The result from the command"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cmd }}
